/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KlassementenModeRouteImport } from './routes/klassementen.$mode'
import { Route as VerenigingenClubIdRouteImport } from './routes/verenigingen.$clubId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KlassementenModeRoute = KlassementenModeRouteImport.update({
  id: '/klassementen/$mode',
  path: '/klassementen/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const VerenigingenClubIdRoute = VerenigingenClubIdRouteImport.update({
  id: '/verenigingen/$clubId',
  path: '/verenigingen/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/klassementen/$mode': typeof KlassementenModeRoute
  '/verenigingen/$clubId': typeof VerenigingenClubIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/klassementen/$mode': typeof KlassementenModeRoute
  '/verenigingen/$clubId': typeof VerenigingenClubIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/klassementen/$mode': typeof KlassementenModeRoute
  '/verenigingen/$clubId': typeof VerenigingenClubIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/klassementen/$mode' | '/verenigingen/$clubId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/klassementen/$mode' | '/verenigingen/$clubId'
  id: '__root__' | '/' | '/klassementen/$mode' | '/verenigingen/$clubId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KlassementenModeRoute: typeof KlassementenModeRoute
  VerenigingenClubIdRoute: typeof VerenigingenClubIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klassementen/$mode': {
      id: '/klassementen/$mode'
      path: '/klassementen/$mode'
      fullPath: '/klassementen/$mode'
      preLoaderRoute: typeof KlassementenModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verenigingen/$clubId': {
      id: '/verenigingen/$clubId'
      path: '/verenigingen/$clubId'
      fullPath: '/verenigingen/$clubId'
      preLoaderRoute: typeof VerenigingenClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KlassementenModeRoute: KlassementenModeRoute,
  VerenigingenClubIdRoute: VerenigingenClubIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
